# Generated by Django 4.2.11 on 2024-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNO', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Bless', models.CharField(max_length=50)),
            ],
        ),
    ]
